### ISSUE TITLE
Update p2sh-p2wsh vsize estimation to use tools from p2wsh

### ISSUE THREAD

**Issue by bucko13** [unchained-capital/unchained-bitcoin#12]
The fee estimation for p2wsh was found to be off by a small fraction in the case of a tx of particular make-up that caused the estimated size to undercount by 1 byte. To fix this a change was merged in #11 to be more exact with the estimates. 

Many of the methods for calculating used in the p2wsh estimation could be used for other transaction types as well and the utility functions used in `p2wsh.js` should be abstracted for these use cases. This makes the code more flexible and avoids p2sh-p2wsh potentially having the same kind of edge case as we found with p2wsh. This is not critical but would be a very useful update.

**Comment by jevidon** [comment]
Closed due to inactivity. Future development to happen in the monorepo: https://github.com/caravan-bitcoin/caravan
