### ISSUE TITLE
validateExtendedPublicKey needs SLIP132 and regtest

### ISSUE THREAD

**Issue by destrys** [unchained-capital/unchained-bitcoin#13]
currently, `validateExtendedPublicKey` only checks for xpub and tpub for networks mainnet and testnet.

Caravan configs currently only export xpubs/tpubs, so if only validates those on reading a config, but when we make Caravan smart enough to read other wallet configs, it will be better to validate the Ypub/Zpub etc instead of converting everything to an xpub first.

And generally, unchained-bitcoins should be SLIP132 aware at a minimum.

Additionally, we should support a REGTEST network type so the apps don't have to change to specify TESTNET even though they are on regtest.

**Comment by jevidon** [comment]
Migrated issue to new repo: https://github.com/caravan-bitcoin/caravan/issues/61
